// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.29.2
// source: api/grpc/usage/subject/subject.proto

package subject

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subject int32

const (
	Subject_Undefined       Subject = 0
	Subject_Interests       Subject = 1
	Subject_PublishHourly   Subject = 2
	Subject_PublishDaily    Subject = 3
	Subject_InterestsPublic Subject = 4
	Subject_Subscriptions   Subject = 5
)

// Enum value maps for Subject.
var (
	Subject_name = map[int32]string{
		0: "Undefined",
		1: "Interests",
		2: "PublishHourly",
		3: "PublishDaily",
		4: "InterestsPublic",
		5: "Subscriptions",
	}
	Subject_value = map[string]int32{
		"Undefined":       0,
		"Interests":       1,
		"PublishHourly":   2,
		"PublishDaily":    3,
		"InterestsPublic": 4,
		"Subscriptions":   5,
	}
)

func (x Subject) Enum() *Subject {
	p := new(Subject)
	*p = x
	return p
}

func (x Subject) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Subject) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_usage_subject_subject_proto_enumTypes[0].Descriptor()
}

func (Subject) Type() protoreflect.EnumType {
	return &file_api_grpc_usage_subject_subject_proto_enumTypes[0]
}

func (x Subject) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Subject.Descriptor instead.
func (Subject) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_usage_subject_subject_proto_rawDescGZIP(), []int{0}
}

var File_api_grpc_usage_subject_subject_proto protoreflect.FileDescriptor

var file_api_grpc_usage_subject_subject_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x75, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x77, 0x61, 0x6b, 0x61, 0x72, 0x69, 0x2e,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2a, 0x74, 0x0a,
	0x07, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x65, 0x64, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x73, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x48, 0x6f, 0x75, 0x72, 0x6c, 0x79, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x10, 0x04,
	0x12, 0x11, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x10, 0x05, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x77, 0x61, 0x6b, 0x61, 0x72, 0x69, 0x2f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_usage_subject_subject_proto_rawDescOnce sync.Once
	file_api_grpc_usage_subject_subject_proto_rawDescData = file_api_grpc_usage_subject_subject_proto_rawDesc
)

func file_api_grpc_usage_subject_subject_proto_rawDescGZIP() []byte {
	file_api_grpc_usage_subject_subject_proto_rawDescOnce.Do(func() {
		file_api_grpc_usage_subject_subject_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_usage_subject_subject_proto_rawDescData)
	})
	return file_api_grpc_usage_subject_subject_proto_rawDescData
}

var file_api_grpc_usage_subject_subject_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_grpc_usage_subject_subject_proto_goTypes = []interface{}{
	(Subject)(0), // 0: awakari.usage.subject.Subject
}
var file_api_grpc_usage_subject_subject_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_usage_subject_subject_proto_init() }
func file_api_grpc_usage_subject_subject_proto_init() {
	if File_api_grpc_usage_subject_subject_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_usage_subject_subject_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_grpc_usage_subject_subject_proto_goTypes,
		DependencyIndexes: file_api_grpc_usage_subject_subject_proto_depIdxs,
		EnumInfos:         file_api_grpc_usage_subject_subject_proto_enumTypes,
	}.Build()
	File_api_grpc_usage_subject_subject_proto = out.File
	file_api_grpc_usage_subject_subject_proto_rawDesc = nil
	file_api_grpc_usage_subject_subject_proto_goTypes = nil
	file_api_grpc_usage_subject_subject_proto_depIdxs = nil
}
