syntax = "proto3";

package awakari.subscriptions;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

option go_package = "./api/grpc";

service Service {
  rpc Update(UpdateRequest) returns (UpdateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
  rpc ListByInterest(ListByInterestRequest) returns (ListByInterestResponse);
  rpc Count(CountRequest) returns (CountResponse);
  rpc DeleteExtra(DeleteExtraRequest) returns (DeleteExtraResponse);
  rpc ChangeOwner(ChangeOwnerRequest) returns (ChangeOwnerResponse);
}

enum Format {
  Rss = 0;
  CeJs = 1;
  Html = 2;
}

message Subscription {
  string groupId = 1;
  string userId = 2;
  string url = 3;
  Format format = 4;
  bytes secret = 5;
  google.protobuf.Timestamp lastResultAt = 6;
  google.protobuf.Duration intervalMin = 7;
  uint32 errorCount = 8;
}

message UpdateRequest {

  // query fields
  string interestId = 1;
  string groupId = 2;
  string userId = 3;
  string url = 4;

  // set fields
  google.protobuf.Timestamp lastResultAt = 5;
  bool deliveryFailure = 7;
}

message UpdateResponse {
}

message DeleteRequest {
  string interestId = 1;
  string groupId = 2;
  string userId = 3;
  string url = 4;
}

message DeleteResponse {
}

message ListByInterestRequest {
  string interestId = 1;
  string cursor = 2;
  uint32 limit = 3;
}

message ListByInterestResponse {
  repeated Subscription page = 1;
}

// Count

message CountRequest {
  Filter filter = 1;
  uint32 limit = 2;
}

message CountResponse {
  int64 count = 1;
}

message Filter {
  string id = 1;
  string groupId = 2;
  string userId = 3;
}

// DeleteExtra

message DeleteExtraRequest {
  Filter filter = 1;
  uint32 limit = 2;
}

message DeleteExtraResponse {
  int64 countLeft = 1;
  int64 countDeleted = 2;
}

// ChangeOwner

message ChangeOwnerRequest {
  string oldGroupId = 1;
  string oldUserId = 2;
  string newGroupId = 3;
  string newUserId = 4;
}

message ChangeOwnerResponse {
  int64 n = 1;
}
