apiVersion: v1
kind: Service
metadata:
  name: {{ include "subscriptions.fullname" . }}
  labels:
    {{- include "subscriptions.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.service.metrics.port }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.ingressHttpV1.enabled }}
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "subscriptions.selectorLabels" . | nindent 4 }}
